<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_alien.png</name>
   <tag></tag>
   <elementGuidId>5019dc0e-ba87-4fb0-8524-dd59f48cde0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='drag-drop-upload']/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5c1c1535-cf04-4465-a8f4-bbd2c2e813fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>alien.png</value>
      <webElementGuid>0682be28-c004-4b5d-afaf-e45b017d7bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drag-drop-upload&quot;)/div[@class=&quot;dz-preview dz-processing dz-image-preview dz-success dz-complete&quot;]/div[@class=&quot;dz-details&quot;]/div[@class=&quot;dz-filename&quot;]/span[1]</value>
      <webElementGuid>90b18b7e-f9f4-496b-b42b-952e0c338cd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='drag-drop-upload']/div/div/div/span</value>
      <webElementGuid>ecf6fc40-7870-44fc-88c8-490a4d1ac3f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='File Uploader'])[1]/following::span[1]</value>
      <webElementGuid>31bf0f75-4da4-4880-ae7e-943df246d9a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='✔'])[1]/preceding::span[1]</value>
      <webElementGuid>5dd543e4-d1d8-4657-aee4-06eba9b39ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='✔'])[2]/preceding::span[3]</value>
      <webElementGuid>c230c6d3-46d3-4548-8749-abf486ec4578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='alien.png']/parent::*</value>
      <webElementGuid>a27f187f-50b9-4207-bf47-076d5a1bfe47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>e63479ce-2994-46fb-abf0-276501f1df91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'alien.png' or . = 'alien.png')]</value>
      <webElementGuid>4cf41996-1da5-4faa-8752-de8f152a5f48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
